name: docker-build-custom-action
description: docker build
inputs:
  path_dockerfile:
    description: "path for the docker file"
    required: false
    default: "Dockerfile"
  image_name:
    description: "custom name for the image"
    required: false
    default: "cicdimage"
  tag_name:
    description: "tag name"
    required: false
    default: 'name tag'
runs:
  using: composite
  steps:
    - run: |
        tagVar = ""
        if [ -z "${{ inputs.tag_name }}" ]; then
          tagVar = $(date +%s)"
          echo "TAG=$tagVar" >> $GITHUB_ENV
        else
          tagVar = ${{ inputs.tag_name }}
          echo "TAG=$tagVar" >> $GITHUB_ENV
        fi
        
        docker build . --file ${{inputs.path_dockerfile}} --tag ${{inputs.image_name}}:$tagVar
        
        echo "DOCKER_IMAGE_NAME=${{inputs.image_name}}:$tagVar" >> $GITHUB_ENV
      shell: bash