name: docker-build-custom-action
description: docker build
inputs:
  path_dockerfile:
    description: "path for the docker file"
    required: false
    default: "Dockerfile"
  image_name:
    description: "custom name for the image"
    required: false
    default: "cicdimage"
  tag_name:
    description: "tag name"
    required: false
    default: 'name tag'
runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
      shell: bash

    - run: |
        NAME=${{inputs.image_name}}:${{env.TAG}}
        echo "DOCKER_IMAGE_NAME=$NAME" >> $GITHUB_ENV
        
        docker build . --file ${{inputs.path_dockerfile}} --tag $NAME
        
      shell: bash