name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      uses: simaomata13/academy/.github/actions/docker_build@main
      with:
        path_dockerfile: Dockerfile
        image_name: cicdimage2
        tag_name: 1212131

    - name: List Docker images
      run: docker image list
